---
apiVersion: v2
name: cronjobs
description: A generic helm cronjob chart for kubernetes
type: application
version: 1.6.2
appVersion: latest
home: https://github.com/klicktipp/helm-charts
keywords:
  - cronjob
sources:
  - https://github.com/klicktipp/helm-charts
annotations:
  artifacthub.io/links: |
    - name: Image source
      url: https://github.com/docker-library/busybox
    - name: Image DockerHub
      url: https://hub.docker.com/_/busybox
dependencies:
  - name: common
    version: 2.36.0
    repository: https://charts.bitnami.com/bitnami
