---
apiVersion: v1
appVersion: 2.7.1
description: ProxySQL Helm chart for Kubernetes
name: proxysql
version: 1.1.1
home: https://www.proxysql.com/
sources:
  - https://github.com/dysnix/charts
  - https://github.com/sysown/proxysql
maintainers:
  - email: services@dysnix.com
    name: Dysnix
