apiVersion: v2
name: redisinsight
version: 0.4.0
description: RedisInsight - The GUI for Redis
type: application
keywords:
  - redis
  - gui
home: https://redis.com/redis-enterprise/redis-insight/
appVersion: 1.14.0
