---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pdns.fullname" . }}
  labels:
    {{- include "pdns.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "pdns.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pdns.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmaps.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "pdns.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . | quote }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- else if ne (default "soft" .Values.podAntiAffinity.type) "disabled" }}
      affinity:
        podAntiAffinity:
          {{- $instanceLabel := .Release.Name }}
          {{- $topologyKey := default "kubernetes.io/hostname" .Values.podAntiAffinity.topologyKey }}
          {{- if eq (default "soft" .Values.podAntiAffinity.type) "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                      - {{ $instanceLabel }}
              topologyKey: {{ $topologyKey | quote }}
          {{- else }}
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/instance
                      operator: In
                      values:
                        - {{ $instanceLabel }}
                topologyKey: {{ $topologyKey | quote }}
          {{- end }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "pdns.image" . | quote }}
          imagePullPolicy: {{ default .Values.image.imagePullPolicy .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          ports:
            - name: dns-udp
              containerPort: {{ .Values.pdns.port }}
              protocol: UDP
            - name: dns-tcp
              containerPort: {{ .Values.pdns.port }}
              protocol: TCP
            {{- if or .Values.pdns.api.enabled (include "pdns.podMonitorEnabled" . | trim | eq "true") }}
            - name: api
              containerPort: {{ .Values.pdns.api.port }}
              protocol: TCP
            {{- end }}
          livenessProbe:
            tcpSocket:
              port: dns-tcp
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
          readinessProbe:
            tcpSocket:
              port: dns-tcp
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: pdns-config
              mountPath: /etc/powerdns/recursor.yml
              subPath: recursor.yml
            {{- if or .Values.pdns.lua.enabled .Values.pdns.config.recursor.lua_config_file }}
            - name: pdns-lua
              mountPath: /etc/powerdns/recursor.lua
              subPath: recursor.lua
            {{- end }}
      volumes:
        - name: pdns-config
          configMap:
            name: {{ include "pdns.fullname" . }}-config
        {{- if or .Values.pdns.lua.enabled .Values.pdns.config.recursor.lua_config_file }}
        - name: pdns-lua
          configMap:
            name: {{ include "pdns.fullname" . }}-lua
        {{- end }}
