---
apiVersion: v2
name: rabbitmq-cluster
description: Helm chart to define a RabbitMQ cluster via official rabbitmq.com CRDs (RabbitmqCluster).
type: application
version: 2.2.1
appVersion: "4.2-management"
kubeVersion: ">= 1.33.0-0"
home: https://www.rabbitmq.com/kubernetes/operator/operator-overview.html
sources:
  - https://github.com/CloudPirates-io/helm-charts/tree/main/charts/rabbitmq-cluster-operator
keywords:
  - cloudpirates
  - rabbitmq
  - operator
  - crd
  - messaging
  - amqp
