---
apiVersion: v2
name: rabbitmq-topology
description: Helm chart to manage RabbitMQ topology resources via RabbitMQ Topology Operator CRDs.
type: application
version: "1.0.0"
appVersion: "4.2-management"
kubeVersion: ">= 1.33.0-0"
home: https://www.rabbitmq.com/kubernetes/operator/using-topology-operator
keywords:
  - rabbitmq
  - topology
  - operator
  - messaging
  - amqp
dependencies:
  - name: klicktipp-common
    version: 1.0.0
    repository: "file://../klicktipp-common"
