apiVersion: v2
name: powerdns-recursor
description: Helm chart for deploying PowerDNS Recursor on Kubernetes
type: application
version: 0.1.0
appVersion: "5.3.4"
keywords:
  - dns
  - powerdns
  - recursor
home: https://www.powerdns.com/
sources:
  - https://github.com/PowerDNS/pdns
