---
apiVersion: v2
name: rspamd
description: A Helm chart for deploying Rspamd on Kubernetes
type: application
version: 1.2.0
# renovate: datasource=docker depName=rspamd/rspamd
appVersion: "3.13.2"
keywords:
  - rspamd
  - spam-filter
  - mta
  - email
home: https://github.com/klicktipp/helm-charts
icon: https://avatars.githubusercontent.com/u/21975367?s=200&v=4
sources:
  - https://github.com/rspamd/rspamd
  - https://rspamd.com
maintainers:
  - name: vquie
    url: https://github.com/vquie
    email: vitali.quiering@klick-tipp.team
