{{- if .Values.ingress.enabled }}
{{- $fullName := include "rspamd.fullname" . }}
{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
---
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "rspamd.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | default $.Values.global.baseURL | quote }}
      http:
        paths:
          {{- range .paths }}
          {{- $backend := (.backend | default dict) }}
          {{- $serviceName := (get $backend "serviceName" | default (get $backend "service") | default $fullName) }}
          {{- $servicePort := (get $backend "servicePort" | default (get $backend "port") | default $.Values.services.worker) }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
              {{- else }}
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
              {{- end }}
          {{- end }}
    {{- end }}

{{- if .Values.ingress.singlePodPaths.enabled }}
---
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-single-pods
  labels:
    {{- include "rspamd.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | default $.Values.global.baseURL | quote }}
      http:
        paths:
          {{- if $.Values.multiTenancy }}
          {{- range $tenant, $_ := $.Values.config }}
          - path: /{{ $tenant }}(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}-{{ $tenant }}
                port:
                  number: {{ $.Values.services.worker }}
              {{- else }}
              serviceName: {{ $fullName }}-{{ $tenant }}
              servicePort: {{ $.Values.services.worker }}
              {{- end }}
          {{- range $index := until (int $.Values.replicaCount) }}
          - path: /rspamd-{{ $tenant }}-{{ $index }}(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}-{{ $tenant }}-{{ $index }}
                port:
                  number: {{ $.Values.services.controller }}
              {{- else }}
              serviceName: {{ $fullName }}-{{ $tenant }}-{{ $index }}
              servicePort: {{ $.Values.services.controller }}
              {{- end }}
          {{- end }}
          {{- end }}
          {{- else }}
          {{- range $index := until (int $.Values.replicaCount) }}
          - path: /rspamd-{{ $index }}(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}-{{ $index }}
                port:
                  number: {{ $.Values.services.controller }}
              {{- else }}
              serviceName: {{ $fullName }}-{{ $index }}
              servicePort: {{ $.Values.services.controller }}
              {{- end }}
          {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
{{- end }}
