{{- if .Values.extraSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rspamd.fullname" . }}-secretvars
  labels:
    {{- include "rspamd.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.extraSecrets }}
  RSPAMD_{{ $key }}: {{ $val | b64enc }}
  {{- end }}
{{- end }}
