# Title: Users from existing secrets (e.g. 1Password)
rabbitmq-topology:
  enabled: true
  rabbitmq:
    topology:
      users:
        app-user:
          metadataName: app-user
          existingSecret: rabbitmq-user-app
          permission:
            referenceType: userReference
            metadataName: app-user
            enabled: true
            vhost: "/"
            configure: ".*"
            write: ".*"
            read: ".*"
