# Title: Users with chart-managed secrets
rabbitmq-topology:
  enabled: true
  rabbitmq:
    topology:
      users:
        smtp-user:
          metadataName: smtp-user
          password: "change-me"
          permission:
            referenceType: userReference
            metadataName: smtp-user
            enabled: true
            vhost: "/"
            configure: ".*"
            write: ".*"
            read: ".*"
