---
# pod disruption budget
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: airbyte-rabbitmq
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: airbyte-rabbitmq
