---
{{- if .Values.rabbitmq.vhost.enabled }}
{{- $clusterRef := .Values.rabbitmq.cluster.name | default (include "rabbitmq-cluster.fullname" .) }}
apiVersion: rabbitmq.com/v1beta1
kind: Vhost
metadata:
  name: {{ .Values.rabbitmq.cluster.name | default (include "rabbitmq-cluster.fullname" .) }}
  labels:
    {{- include "rabbitmq-cluster.labels" . | nindent 4 }}
spec:
  name: {{ .Values.rabbitmq.vhost.name | quote }}
  rabbitmqClusterReference:
    name: {{ $clusterRef | quote }}
{{- end }}
