---
apiVersion: v2
name: zalando-postgres-cluster
description: Creates a postgres cluster using the Zalando Postgres operator and local storage
type: application
version: 1.1.2
appVersion: 1.15.1
keywords:
  - postgres
  - cluster
  - operator
  - zalando
icon: https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Postgresql_elephant.svg/1200px-Postgresql_elephant.svg.png
sources:
  - https://github.com/zalando/postgres-operator
maintainers:
  - name: KlickTipp DevOps Team
